### ISSUE TITLE
Contrast Login

### ISSUE THREAD

**Issue by techmefr** [WildCodeSchool/Lyon-JS-09-23-P3-airnbb#62]
Améliorer les contrastes du formulaire login, email et mot de passe sont peu lisible
![image](https://github.com/WildCodeSchool/Lyon-JS-09-23-P3-airnbb/assets/51131564/073cce07-f617-4899-8cef-a800476b9e5b)

**Comment by Al-lien** [comment]
Corrigé dans la PR #78
