### ISSUE TITLE
Login - Création d'un compte

### ISSUE THREAD

**Issue by techmefr** [WildCodeSchool/Lyon-JS-09-23-P3-airnbb#63]
le bouton devient accessible dès qu'on rentre un mot de passe, les champs ne sont pas obligatoires mais la création de compte ne fonctionne pas sans ça
![image](https://github.com/WildCodeSchool/Lyon-JS-09-23-P3-airnbb/assets/51131564/c934be3f-081f-4182-a0dd-281311769400)

**Comment by Al-lien** [comment]
Corrigé dans la PR #79
