### ISSUE TITLE
Information sur l'enfant illisible

### ISSUE THREAD

**Issue by techmefr** [WildCodeSchool/Lyon-JS-09-23-P3-airnbb#65]
Quand on a créé un enfant on arrive sur une page mais c'est illisble
![image](https://github.com/WildCodeSchool/Lyon-JS-09-23-P3-airnbb/assets/51131564/467ddaab-58cb-4c69-bf87-4e7304eb37ca)

**Comment by Cricri1993** [comment]
Font-size modifiée
