### ISSUE TITLE
Home - élément qui se chevauche et contraste peu lisible

### ISSUE THREAD

**Issue by techmefr** [WildCodeSchool/Lyon-JS-09-23-P3-airnbb#67]
Sur la page home sous firefox zoom 100%, la sidebar chevauche les éléments
De plus les textes dans les images sont peu lisibles, le blanc sur des couleurs claires ça n'aide pas
![image](https://github.com/WildCodeSchool/Lyon-JS-09-23-P3-airnbb/assets/51131564/070e7e87-51e5-4693-83da-248c45345d60)

**Comment by Cricri1993** [comment]
Image assombrie avec un filtre. Pas de soucis de chevauchements pourtant...
